export const TeamObj = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Get to know us",
  headline: "Our Team",
  description: ["The Visionary", "The Creative", "The Leader", "YOU"],
  buttonLabel: "Start Now",
  imgStart: false,
  img1: require("../../images/Master-1.png"),
  img2: require("../../images/Master-2.png"),
  img3: require("../../images/Master-3.png"),
  img4: require("../../images/Master-4.png"),
  alt: "Papers",
  dark: false,
  primary: false,
  darkText: true,
};
